name: PublishDocumentation

on:
  push:
    branches:
      - main

jobs:
  doc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Publish Jazzy Docs
      uses: steven0351/publish-jazzy-docs@v1
      with:
        personal_access_token: ${{ secrets.DOC_ACCESS_TOKEN }}
