name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Lint PR code
      uses: norio-nomura/action-swiftlint@3.2.1
      env:
        DIFF_BASE: ${{ github.base_ref }}

    - name: Run tests
      run: swift test
